<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="s3.ind.business.impl.UserServiceImplTest" tests="10" skipped="0" failures="0" errors="0" timestamp="2024-05-04T22:21:09" hostname="DESKTOP-88OFGPG" time="2.791">
  <properties/>
  <testcase name="createUser_Successful()" classname="s3.ind.business.impl.UserServiceImplTest" time="2.674"/>
  <testcase name="checkUserPermission()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.005"/>
  <testcase name="getAllUsers()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.005"/>
  <testcase name="updateUser()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.006"/>
  <testcase name="createUser_EmailAlreadyExists()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.046"/>
  <testcase name="getAllTrainers()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.005"/>
  <testcase name="createTrainer()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.006"/>
  <testcase name="createUser()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.007"/>
  <testcase name="deleteUser()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.007"/>
  <testcase name="getUserById()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.006"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
